enum Names {
    Edit_Distance = 'edit-distance',
    Knapsack_Problem = 'knapsack-problem',
    RodCutting_Problem = 'rod-cutting-problem',
    Wildcard_Matching = 'wildcard-matching',
    Regular_Expression = 'regular-expression-matching',
    Coin_Change_Fewest_Number = 'coin-change-fewest-number',
    Coin_Change_How_Many_Ways = 'coin-change-how-many-ways',
    Is_Subsequence = 'is-subsequence',
    EggDropping_Problem = 'egg-dropping-problem',
    Word_Break = 'word-break-one',
    Minimum_Path_Sum = 'minimum-path-sum',
    Longest_Common_Subsequence = 'longest-common-subsequence',
    Longest_Common_Substring = 'longest-common-substring',
    Maximum_Subarray_Problem = 'maximum-subarray-problem',
    Subset_Sum_Problem = 'subset-sum-problem',
    Longest_Palindromic_Subsequence = 'longest-palindromic-subsequence',
    Longest_Palindromic_Substring = 'longest-palindromic-substring',
    Palindrome_Partitioning = 'palindrome-partitioning',
    Longest_Increasing_Subsequence = 'longest-increasing-subsequence',
    Longest_Increasing_Subsequence_II = 'longest-increasing-subsequence-two',
    Minimum_Number_Jumps_To_End = 'minimum-number-of-jumps-to-reach-end',
}

export default Names;
