export const OPEN_DIALOG_CLICK = '@@EDIT_DISTANCE/OPEN_DIALOG_CLICK';
export type OPEN_DIALOG_CLICK = typeof OPEN_DIALOG_CLICK;

export const CLOSE_DIALOG_CLICK = '@@EDIT_DISTANCE/CLOSE_DIALOG_CLICK';
export type CLOSE_DIALOG_CLICK = typeof CLOSE_DIALOG_CLICK;

export const OPEN_FORMULA_CLICK = '@@EDIT_DISTANCE/OPEN_FORMULA_CLICK';
export type OPEN_FORMULA_CLICK = typeof OPEN_FORMULA_CLICK;

export const CLOSE_FORMULA_CLICK = '@@EDIT_DISTANCE/CLOSE_FORMULA_CLICK';
export type CLOSE_FORMULA_CLICK = typeof CLOSE_FORMULA_CLICK;

export const BUTTON_CLICK = '@@EDIT_DISTANCE/BUTTON_CLICK';
export type BUTTON_CLICK = typeof BUTTON_CLICK;

export const REFRESH_CLICK = '@@EDIT_DISTANCE/REFRESH_CLICK';
export type REFRESH_CLICK = typeof REFRESH_CLICK;

export const GET_RECORD = '@@EDIT_DISTANCE/GET_SUCCESS_COUNT';
export type GET_RECORD = typeof GET_RECORD;

export const RECEIVED_RECORD = '@@EDIT_DISTANCE/RECEIVED_SUCCESS_COUNT';
export type RECEIVED_RECORD = typeof RECEIVED_RECORD;

export const INCREASE_RECORD = '@@EDIT_DISTANCE/INCREASE_RECORD';
export type INCREASE_RECORD = typeof INCREASE_RECORD;
