export const enum ActionTypes {
    BUTTON_CLICK = '@@EDIT_DISTANCE/BUTTON_CLICK',
    OPEN_DIALOG_CLICK = '@@EDIT_DISTANCE/OPEN_DIALOG_CLICK',
    CLOSE_DIALOG_CLICK = '@@EDIT_DISTANCE/CLOSE_DIALOG_CLICK',
    REFRESH_CLICK = '@@EDIT_DISTANCE/REFRESH_CLICK',
    GET_RECORD = '@@EDIT_DISTANCE/GET_SUCCESS_COUNT',
    RECEIVED_RECORD = '@@EDIT_DISTANCE/RECEIVED_SUCCESS_COUNT',
    INCREASE_RECORD = '@@EDIT_DISTANCE/INCREASE_RECORD',
}
